CREATE TABLE t (id INT, age INT, PRIMARY KEY (id));
INSERT INTO t VALUES (1, 10);
INSERT INTO t VALUES (2, 20);
INSERT INTO t VALUES (3, 1);
SELECT * FROM t;
UPDATE t SET id = 100 WHERE age = 1;
SELECT * FROM t;




